name: CI/CD Spring

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test

  deploy-prod:
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: prod
        run: mvn clean install -DskipTests

      - name: print pwd
        run: |
          pwd
          ls

      - name: Set up SSH agent
        id: ssh-agent-setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to the agent and configure known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
          EC2_INSTANCE_IP: ${{ secrets.IP_VPC }}
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./target/library-0.0.1-SNAPSHOT.jar ec2-user@$EC2_INSTANCE_IP:/home/ec2-user/
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_INSTANCE_IP java -jar /home/ec2-user/library-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod