name: CI/CD Spring

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test

  deploy-prod:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: prod
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: set ssh key
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY }}
            run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
              chmod 600 key.pem
              scp -i key.pem -o "StrictHostKeyChecking=no" library-0.0.1-SNAPSHOT.jar ec2-user@${{secrets.IP_VPC}}
              java -jar library-0.0.1-SNAPSHOT.jar
              

      - name: pwd
        run: |
          ls
          ls target

#      - name: Deploy to production EC2 instance
#        env:
#          EC2_INSTANCE_IP: ${{ secrets.IP_VPC }}
#        run: |
#          scp -o StrictHostKeyChecking=no -r target/library-0.0.1-SNAPSHOT.jar ec2-user@$EC2_INSTANCE_IP
#          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE_IP